



spring.application.name=FitManage-Pro
# Habilita o console no navegador
spring.h2.console.enabled=true
#atualiza automaticamente
spring.jpa.hibernate.ddl-auto=update
# Define o caminho para acessar (localhost:8080/h2-console)
spring.h2.console.path=/h2-console
# Define uma URL fixa para facilitar o login
spring.datasource.url=jdbc:h2:mem:academiadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=